#+TITLE: curlew
#+AUTHOR: dfireBird

Curlew is the API to manage a Team separated by cluster.

You can add members to the Team, add them to cluster, provide report
and remarks.

* Endpoints
Documentation on what an endpoint does is detailed on the docs folder
The list of endpoints:
** Authentication
More details [[file:docs/auth.org][here]].
+ =POST /auth=
** Availability
More details [[file:docs/availability.org][here]].
+ =GET /availability=
+ =POST /availability=
+ =GET /availability/desc=
+ =POST /availability/desc=
+ =GET /availabilities=
** Report
More details [[file:docs/report.org][here]].
+ =GET /reports=
+ =POST /report=
** Social Media
More details [[file:docs/social.org][here]].
+ =GET /social=
+ =POST /social=
** Events
More details [[file:docs/events.org][here]].
+ =GET /events=
+ =POST /event=
** Images
More details [[file:docs/images.org][here]].
+ =GET /images=
+ =POST /image=
** Resource
More details [[file:docs/resource.org][here]].
+ =GET /resources=
+ =POST /resource=
** Team Members
More details [[file:docs/team.org][here]].
+ =GET /team=
+ =POST /team=
** Remarks
More details [[file:docs/remark.org][here]].
+ =GET /remarks=
+ =POST /remark=
* Deployment
Create a .env file with the following information:
#+BEGIN_SRC 
POSTGRES_USER=<postrgres_username>
POSTGRES_PASSWORD=<postrgres_password>
POSTGRES_DB=<postgres_db_name>
#+END_SRC

** Docker-Based
*** Prerequisite
+ Docker
+ docker-compose

Run the docker-compose to start the API server.

#+BEGIN_SRC bash
$ docker-compose up
#+END_SRC

** Local Deployment (Without Docker)
*** Prerequisite
+ postgres
+ node version > 12
+ yarn

Install the node dependencies 
#+BEGIN_SRC bash
$ yarn
#+END_SRC

Ensure that you have postrgres installed and it's running on your system
then start the server.
#+BEGIN_SRC bash
$ yarn start
#+END_SRC

* Usage
Navigate to =localhost:8000= and access the endpoints
* License
This project uses a MIT License, which can be viewed here [[file:LICENSE][here]].
